# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nubia/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter nx606j nx616j nx619j,$(TARGET_DEVICE)),)

endif
